### ISSUE TITLE
Https connection certificates issue

### ISSUE THREAD

**Issue by hbers** [equeim/tremotesf-android#17]
Https connection with self signed certificate option doesn't work after version 1.6.2 . I updated to the newest version and was unable to connect to the server over https with the same config. I deleted all the data and rewrote the config yet it didn't work.

**Comment by equeim** [comment]
Thanks for the info. It seems that it has broke when I moved to C++/Qt network backend. I suspect that there is something wrong with Java binding for libtremotesf, so that certificates don't load properly. Unfortunately, I will not have access to my PC for a few weeks so I won't be able to fix it until then.

**Comment by equeim** [comment]
@hbers How did you set up SSL? I found out that Qt Network does not support IP entries in Subject Alternative Name extension. You should use DNS entry with ip address instead. Maybe this is the case.

**Comment by hbers** [comment]
Sadly I'm not savvy enough on this subject to give a satisfying response to your question. I merely experienced my configuration no longer working and reported it. If you tried an SSL setup configured like you suggested and it worked out I guess that explains it.

**Comment by equeim** [comment]
@hbers transmission-daemon does not support HTTPS by itself. You need to use a proxy web server (e.g. lighttpd) for it. I wanted to know how you configured it because I'm not experienced in SSL either. I just was able to set it up so that it works (using google), but I don't know whether my setup is correct or whether if tremotesf uses certificates correctly.

**Comment by hbers** [comment]
Alright, here is a certificate that I just created that doesn't work with tremotesf. Alongside the certificate I'm putting the config file for nginx. sites-enabled/default file
Github doesn't support uploading key files so I'm renaming it to txt. 
[cert1.txt](https://github.com/equeim/tremotesf-android/files/2263932/cert1.txt)
[cert1.pem.txt](https://github.com/equeim/tremotesf-android/files/2263937/cert1.pem.txt)

[default.txt](https://github.com/equeim/tremotesf-android/files/2263939/default.txt)

**Comment by equeim** [comment]
Okay, it seems that problem is that your certificate does not have Common Name field or Subject Alternative Names, which causes SSL handshake to fail because the hostname (or ip address) that tremotesf connects to doesn't match certificate's hostname. I think that the correct fix would be to ignore this error if certificate using by server matches the one in tremotesf configurations.

**Comment by equeim** [comment]
Fixed in https://github.com/equeim/libtremotesf/commit/00ee56cb5b4374dc69a4703078dbb015560ec7ce.

**Comment by hbers** [comment]
Great! Thank you.
