### ISSUE TITLE
Issue with certificate

### ISSUE THREAD

**Issue by azlux** [equeim/tremotesf-android#18]
Hi,
Since few weeks, termotesf don't work anymore on my android ("connection error".
I've the version : 1.8.3
I've open the logcat and I've see this warning.
```
09-17 21:06:21.395 25008 25024 W : (null):0 ((null)): "The issuer certificate of a locally looked up certificate could not be found"
09-17 21:06:21.395 25008 25024 W : (null):0 ((null)): QNetworkReply::NetworkError(SslHandshakeFailedError) "SSL handshake failed"
09-17 21:06:21.396 25008 25024 D : (null):0 ((null)): disconnected
```

My certificate is signed by let's encrypt and is valide.

Az

**Comment by azlux** [comment]
It was working before, 2 or 3 months ago.
I think is was in 1.6.0
I didn't add the certificate since let's encrypt renew the certificate every 3 months.
" you connect as-is ?" I have a reverse-proxy (nginx) who manage the SSL and redirect the https on the good port.

**Comment by equeim** [comment]
Did you update/reinstall your Android ROM since then? If you open Android's Settings app, go to “Security & location” -> “Encryption & credentials” -> “Trusted credentials”, can you find "Digital Signature Trust Co. (DST Root CA X3)" there? Anyway, what's your complete certificate chain? Also try to connect using 1.6.3 version (it inside zip). 
[app-fdroid-release.zip](https://github.com/equeim/tremotesf-android/files/2390039/app-fdroid-release.zip)

**Comment by azlux** [comment]
The certificate is the same as https://azlux.fr
Tremotesf v1.6.3 is working well.

**Comment by ThaChillera** [comment]
I'm fairly sure I have the same issue, also using letsencrypt, using a wildcard certificate (*.example.com). How did you solve it?

I wanted to verify it using debug tools, but can't due to this QT bug in 5.11.1: https://bugreports.qt.io/browse/QTBUG-69843.

I will try again when I get home, and update you if this is indeed the same issue.

**Comment by equeim** [comment]
Are you sure that you use the latest version? On F-Droid the latest build is 1.8.3, this issue was fixed in 1.8.4.

**Comment by ThaChillera** [comment]
I am indeed on version 1.8.3. When will the FDroid version be updated?

**Comment by azlux** [comment]
@ThaChillera you can install the version v1.6.3 (it's inside this issue). I'm also waiting fot 1.8.3 on fdroid.

**Comment by azlux** [comment]
Available on F-Droid 👍
