### ISSUE TITLE
SSL Handshake failed

### ISSUE THREAD

**Issue by Nomeji** [equeim/tremotesf-android#60]
Since version 2.5.1, whenever I try to connect to my server I get a toaster with: "SSL Handshake failed".

I'm using caddy as proxy and I get this error in logs: TLS handshake error from <ip> EOF.

Did you change anything related to TLS since last version?

EDIT: okay just saw this commit https://github.com/equeim/tremotesf-android/commit/3e61b4440b3f7fe6830ef17397c4faee5ad6a328 hope it fixes the issue. Please flag a new release so I can test. Thanks a lot!

**Comment by equeim** [comment]
That commit fixes issue that was introduced couple of commits earlier and isn't in 2.5.1 so it's not that.
Do you use self signed certificate? Where did you install Tremotesf from, Google Play, F-Drood or GitHub release?

**Comment by Nomeji** [comment]
Since I was going to lose my data anyway, I just tried 2.4.2 and 2.4.0 from F-Droid. The issue is still present. So the problem isn't link to anything you've done in 2.5.1.

I suspect that my device certificates are just expired since I couldn't update in years. I can still connect to transmission via web interface from the same device but I suppose Firefox ship with it's own certificates to prevent the issue.

Not sure if you can update certificates on your side... I will give you logs to confirm that this is really the issue.

-------- Original Message --------

**Comment by Nomeji** [comment]
Here is log file.
[Uploading log.txt…]()

**Comment by equeim** [comment]
It looks like it's related to DST Root CA X3 expiration: https://letsencrypt.org/ru/docs/dst-root-ca-x3-expiration-september-2021/
https://community.letsencrypt.org/t/production-chain-changes/150739

It says that it should still work on Android though. I suspect that's because Tremotesf uses its own bundled version of OpenSSL which rejects Let's Encrypt chain.
If it used default Android TLS implementation then even on older Android versions that don't have ISRG Root X1 root certificate (like yours) it would still work because of this cross-sign stuff. But with bundled OpenSSL it doesn't work because it's more strict. I'm currently researching how to make it behave it like Android's TLS.

**Comment by Nomeji** [comment]
If that's too complicated, maybe adding a "accept all certificates" thing could be a nice temporary solution espacially if only older devces are affected.

-------- Original Message --------

**Comment by equeim** [comment]
It seems that it is not possible to correctly emulate Android behaviour without patching Qt and/or OpenSSL since checking expiration date of root certificates is their design choice, and I'm not confident enough do mess with TLS.
I don't want to add option to completely bypass TLS security either. It is no different then using plain HTTP. If your certificate's root is not supported on device then using self-signed certificate and importing it in Tremotesf will be more secure then blindly trusting any certificate.
I can add a workaround specifically for Let's Encrypt though, it would be easy.

**Comment by Nomeji** [comment]
If adding a workaround for Let's Encrypt is fine for you I would be happy with it.

I just tried to manually add X1 root certificates from Android settings but this doesn't seem to work.

I also tried on a modern device and it works well. The issue only affect my/old devices.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
